FROM golang:1.22.1 AS build

WORKDIR /build

COPY go.mod go.sum ./
COPY *.go Makefile ./
RUN go mod download
RUN make build

FROM ubuntu:latest
WORKDIR /app
COPY --from=build /build/bin ./bin
ENTRYPOINT [ "/app/bin/api" ]