version: '3.9'

services:

  db_postgres:
    image: postgres
    volumes:
      - /mnt/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  go_api:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db_postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}